<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Exécute le seed pour insérer tous les pays et leurs nationalités.
     */
    public function run(): void
    {
        $pays = [
            ['name' => 'Afghanistan', 'nationality' => 'Afghan'],
            ['name' => 'Albanie', 'nationality' => 'Albanais(e)'],
            ['name' => 'Algérie', 'nationality' => 'Algérien(ne)'],
            ['name' => 'Andorre', 'nationality' => 'Andorran(e)'],
            ['name' => 'Angola', 'nationality' => 'Angolais(e)'],
            ['name' => 'Antigua-et-Barbuda', 'nationality' => 'Antiguais(e)/Barbudien(ne)'],
            ['name' => 'Argentine', 'nationality' => 'Argentin(e)'],
            ['name' => 'Arménie', 'nationality' => 'Arménien(ne)'],
            ['name' => 'Australie', 'nationality' => 'Australien(ne)'],
            ['name' => 'Autriche', 'nationality' => 'Autrichien(ne)'],
            ['name' => 'Azerbaïdjan', 'nationality' => 'Azerbaïdjanais(e)'],
            ['name' => 'Bahamas', 'nationality' => 'Bahaméen(ne)'],
            ['name' => 'Bahreïn', 'nationality' => 'Bahreïni'],
            ['name' => 'Bangladesh', 'nationality' => 'Bangladais(e)'],
            ['name' => 'Barbade', 'nationality' => 'Barbadien(ne)'],
            ['name' => 'Bélarus', 'nationality' => 'Biélorusse'],
            ['name' => 'Belgique', 'nationality' => 'Belge'],
            ['name' => 'Belize', 'nationality' => 'Bélizien(ne)'],
            ['name' => 'Bénin', 'nationality' => 'Béninois(e)'],
            ['name' => 'Bhoutan', 'nationality' => 'Bhoutanais(e)'],
            ['name' => 'Bolivie', 'nationality' => 'Bolivien(ne)'],
            ['name' => 'Bosnie-Herzégovine', 'nationality' => 'Bosnien(ne)/Herzégovin(e)'],
            ['name' => 'Botswana', 'nationality' => 'Botswanais(e)'],
            ['name' => 'Brésil', 'nationality' => 'Brésilien(ne)'],
            ['name' => 'Brunei', 'nationality' => 'Brunéien(ne)'],
            ['name' => 'Bulgarie', 'nationality' => 'Bulgare'],
            ['name' => 'Burkina Faso', 'nationality' => 'Burkinabé'],
            ['name' => 'Burundi', 'nationality' => 'Burundais(e)'],
            ['name' => 'Cap-Vert', 'nationality' => 'Capverdien(ne)'],
            ['name' => 'Cambodge', 'nationality' => 'Cambodgien(ne)'],
            ['name' => 'Cameroun', 'nationality' => 'Camerounais(e)'],
            ['name' => 'Canada', 'nationality' => 'Canadien(ne)'],
            ['name' => 'République centrafricaine', 'nationality' => 'Centrafricain(e)'],
            ['name' => 'Tchad', 'nationality' => 'Tchadien(ne)'],
            ['name' => 'Chili', 'nationality' => 'Chilien(ne)'],
            ['name' => 'Chine', 'nationality' => 'Chinois(e)'],
            ['name' => 'Colombie', 'nationality' => 'Colombien(ne)'],
            ['name' => 'Comores', 'nationality' => 'Comorien(ne)'],
            ['name' => 'Congo (Brazzaville)', 'nationality' => 'Congolais(e)'],
            ['name' => 'Costa Rica', 'nationality' => 'Costaricain(e)'],
            ['name' => 'Croatie', 'nationality' => 'Croate'],
            ['name' => 'Cuba', 'nationality' => 'Cubain(e)'],
            ['name' => 'Chypre', 'nationality' => 'Chypriote'],
            ['name' => 'République tchèque', 'nationality' => 'Tchèque'],
            ['name' => 'République démocratique du Congo', 'nationality' => 'Congolais(e)'],
            ['name' => 'Danemark', 'nationality' => 'Danois(e)'],
            ['name' => 'Djibouti', 'nationality' => 'Djiboutien(ne)'],
            ['name' => 'Dominique', 'nationality' => 'Dominiquais(e)'],
            ['name' => 'République dominicaine', 'nationality' => 'Dominicain(e)'],
            ['name' => 'Équateur', 'nationality' => 'Équatorien(ne)'],
            ['name' => 'Égypte', 'nationality' => 'Égyptien(ne)'],
            ['name' => 'Salvador', 'nationality' => 'Salvadorien(ne)'],
            ['name' => 'Guinée équatoriale', 'nationality' => 'Équato-Guinéen(ne)'],
            ['name' => 'Érythrée', 'nationality' => 'Érythréen(ne)'],
            ['name' => 'Estonie', 'nationality' => 'Estonien(ne)'],
            ['name' => 'Eswatini', 'nationality' => 'Eswatinien(ne)'],
            ['name' => 'Éthiopie', 'nationality' => 'Éthiopien(ne)'],
            ['name' => 'Fidji', 'nationality' => 'Fidjien(ne)'],
            ['name' => 'Finlande', 'nationality' => 'Finlandais(e)'],
            ['name' => 'France', 'nationality' => 'Français(e)'],
            ['name' => 'Gabon', 'nationality' => 'Gabonais(e)'],
            ['name' => 'Gambie', 'nationality' => 'Gambien(ne)'],
            ['name' => 'Géorgie', 'nationality' => 'Géorgien(ne)'],
            ['name' => 'Allemagne', 'nationality' => 'Allemand(e)'],
            ['name' => 'Ghana', 'nationality' => 'Ghanaien(ne)'],
            ['name' => 'Grèce', 'nationality' => 'Grec(que)'],
            ['name' => 'Grenade', 'nationality' => 'Grenadien(ne)'],
            ['name' => 'Guatemala', 'nationality' => 'Guatémaltèque'],
            ['name' => 'Guinée', 'nationality' => 'Guinéen(ne)'],
            ['name' => 'Guinée-Bissau', 'nationality' => 'Bissau-Guinéen(ne)'],
            ['name' => 'Guyana', 'nationality' => 'Guyanien(ne)'],
            ['name' => 'Haïti', 'nationality' => 'Haïtien(ne)'],
            ['name' => 'Saint-Siège', 'nationality' => 'Vatican'],
            ['name' => 'Honduras', 'nationality' => 'Hondurien(ne)'],
            ['name' => 'Hongrie', 'nationality' => 'Hongrois(e)'],
            ['name' => 'Islande', 'nationality' => 'Islandais(e)'],
            ['name' => 'Inde', 'nationality' => 'Indien(ne)'],
            ['name' => 'Indonésie', 'nationality' => 'Indonésien(ne)'],
            ['name' => 'Iran', 'nationality' => 'Iranien(ne)'],
            ['name' => 'Irak', 'nationality' => 'Irakien(ne)'],
            ['name' => 'Irlande', 'nationality' => 'Irlandais(e)'],
            ['name' => 'Israël', 'nationality' => 'Israélien(ne)'],
            ['name' => 'Italie', 'nationality' => 'Italien(ne)'],
            ['name' => 'Jamaïque', 'nationality' => 'Jamaïcain(e)'],
            ['name' => 'Japon', 'nationality' => 'Japonais(e)'],
            ['name' => 'Jordanie', 'nationality' => 'Jordanien(ne)'],
            ['name' => 'Kazakhstan', 'nationality' => 'Kazakhstanais(e)'],
            ['name' => 'Kenya', 'nationality' => 'Kényan(e)'],
            ['name' => 'Kiribati', 'nationality' => 'Kiribatien(ne)'],
            ['name' => 'Koweït', 'nationality' => 'Koweïtien(ne)'],
            ['name' => 'Kirghizistan', 'nationality' => 'Kirghize'],
            ['name' => 'Laos', 'nationality' => 'Laotien(ne)'],
            ['name' => 'Lettonie', 'nationality' => 'Letton(ne)'],
            ['name' => 'Liban', 'nationality' => 'Libanais(e)'],
            ['name' => 'Lesotho', 'nationality' => 'Lésothien(ne)'],
            ['name' => 'Libéria', 'nationality' => 'Libérien(ne)'],
            ['name' => 'Libye', 'nationality' => 'Libyen(ne)'],
            ['name' => 'Liechtenstein', 'nationality' => 'Liechtensteinois(e)'],
            ['name' => 'Lituanie', 'nationality' => 'Lituanien(ne)'],
            ['name' => 'Luxembourg', 'nationality' => 'Luxembourgeois(e)'],
            ['name' => 'Madagascar', 'nationality' => 'Malgache'],
            ['name' => 'Malawi', 'nationality' => 'Malawien(ne)'],
            ['name' => 'Malaisie', 'nationality' => 'Malaisien(ne)'],
            ['name' => 'Maldives', 'nationality' => 'Maldivien(ne)'],
            ['name' => 'Mali', 'nationality' => 'Malien(ne)'],
            ['name' => 'Malte', 'nationality' => 'Maltais(e)'],
            ['name' => 'Îles Marshall', 'nationality' => 'Marshallais(e)'],
            ['name' => 'Mauritanie', 'nationality' => 'Mauritanien(ne)'],
            ['name' => 'Maurice', 'nationality' => 'Mauricien(ne)'],
            ['name' => 'Mexique', 'nationality' => 'Mexicain(e)'],
            ['name' => 'Micronésie', 'nationality' => 'Micronésien(ne)'],
            ['name' => 'Moldavie', 'nationality' => 'Moldave'],
            ['name' => 'Monaco', 'nationality' => 'Monégasque'],
            ['name' => 'Mongolie', 'nationality' => 'Mongol(e)'],
            ['name' => 'Monténégro', 'nationality' => 'Monténégrin(e)'],
            ['name' => 'Maroc', 'nationality' => 'Marocain(e)'],
            ['name' => 'Mozambique', 'nationality' => 'Mozambicain(e)'],
            ['name' => 'Birmanie', 'nationality' => 'Birmane'],
            ['name' => 'Namibie', 'nationality' => 'Namibien(ne)'],
            ['name' => 'Nauru', 'nationality' => 'Nauruan'],
            ['name' => 'Népal', 'nationality' => 'Népalais(e)'],
            ['name' => 'Pays-Bas', 'nationality' => 'Néerlandais(e)'],
            ['name' => 'Nouvelle-Zélande', 'nationality' => 'Néo-Zélandais(e)'],
            ['name' => 'Nicaragua', 'nationality' => 'Nicaraguayen(ne)'],
            ['name' => 'Niger', 'nationality' => 'Nigérien(ne)'],
            ['name' => 'Nigeria', 'nationality' => 'Nigérian(e)'],
            ['name' => 'Corée du Nord', 'nationality' => 'Nord-Coréen(ne)'],
            ['name' => 'Macédoine du Nord', 'nationality' => 'Macédonien(ne)'],
            ['name' => 'Norvège', 'nationality' => 'Norvégien(ne)'],
            ['name' => 'Oman', 'nationality' => 'Omanais(e)'],
            ['name' => 'Pakistan', 'nationality' => 'Pakistanais(e)'],
            ['name' => 'Palaos', 'nationality' => 'Palauien(ne)'],
            ['name' => 'État de Palestine', 'nationality' => 'Palestinien(ne)'],
            ['name' => 'Panama', 'nationality' => 'Panaméen(ne)'],
            ['name' => 'Papouasie-Nouvelle-Guinée', 'nationality' => 'Papouasien(ne)'],
            ['name' => 'Paraguay', 'nationality' => 'Paraguayen(ne)'],
            ['name' => 'Pérou', 'nationality' => 'Péruvien(ne)'],
            ['name' => 'Philippines', 'nationality' => 'Philippin(e)'],
            ['name' => 'Pologne', 'nationality' => 'Polonais(e)'],
            ['name' => 'Portugal', 'nationality' => 'Portugais(e)'],
            ['name' => 'Qatar', 'nationality' => 'Qatarien(ne)'],
            ['name' => 'Roumanie', 'nationality' => 'Roumain(e)'],
            ['name' => 'Russie', 'nationality' => 'Russe'],
            ['name' => 'Rwanda', 'nationality' => 'Rwandais(e)'],
            ['name' => 'Saint-Kitts-et-Nevis', 'nationality' => 'Kittitien(ne)/Névésien(ne)'],
            ['name' => 'Sainte-Lucie', 'nationality' => 'Saint-Lucien(ne)'],
            ['name' => 'Saint-Vincent-et-les-Grenadines', 'nationality' => 'Vincentien(ne)'],
            ['name' => 'Samoa', 'nationality' => 'Samoan(e)'],
            ['name' => 'Saint-Marin', 'nationality' => 'Saint-Marinais(e)'],
            ['name' => 'Sao Tomé-et-Principe', 'nationality' => 'Santoméen(ne)'],
            ['name' => 'Arabie saoudite', 'nationality' => 'Saoudien(ne)'],
            ['name' => 'Sénégal', 'nationality' => 'Sénégalais(e)'],
            ['name' => 'Serbie', 'nationality' => 'Serbe'],
            ['name' => 'Seychelles', 'nationality' => 'Seychellois(e)'],
            ['name' => 'Sierra Leone', 'nationality' => 'Sierra-Léonais(e)'],
            ['name' => 'Singapour', 'nationality' => 'Singapourien(ne)'],
            ['name' => 'Slovaquie', 'nationality' => 'Slovaque'],
            ['name' => 'Slovénie', 'nationality' => 'Slovène'],
            ['name' => 'Îles Salomon', 'nationality' => 'Salomonais(e)'],
            ['name' => 'Somalie', 'nationality' => 'Somalien(ne)'],
            ['name' => 'Afrique du Sud', 'nationality' => 'Sud-Africain(e)'],
            ['name' => 'Corée du Sud', 'nationality' => 'Sud-Coréen(ne)'],
            ['name' => 'Soudan du Sud', 'nationality' => 'Sud-Soudanais(e)'],
            ['name' => 'Espagne', 'nationality' => 'Espagnol(e)'],
            ['name' => 'Sri Lanka', 'nationality' => 'Sri-Lankais(e)'],
            ['name' => 'Soudan', 'nationality' => 'Soudanais(e)'],
            ['name' => 'Suriname', 'nationality' => 'Surinamais(e)'],
            ['name' => 'Suède', 'nationality' => 'Suédois(e)'],
            ['name' => 'Suisse', 'nationality' => 'Suisse'],
            ['name' => 'Syrie', 'nationality' => 'Syrien(ne)'],
            ['name' => 'Tadjikistan', 'nationality' => 'Tadjik'],
            ['name' => 'Tanzanie', 'nationality' => 'Tanzanien(ne)'],
            ['name' => 'Thaïlande', 'nationality' => 'Thaïlandais(e)'],
            ['name' => 'Timor-Leste', 'nationality' => 'Timorais(e)'],
            ['name' => 'Togo', 'nationality' => 'Togolais(e)'],
            ['name' => 'Tonga', 'nationality' => 'Tongien(ne)'],
            ['name' => 'Trinité-et-Tobago', 'nationality' => 'Trinidadien(ne)/Tobagonien(ne)'],
            ['name' => 'Tunisie', 'nationality' => 'Tunisien(ne)'],
            ['name' => 'Turquie', 'nationality' => 'Turc(que)'],
            ['name' => 'Turkménistan', 'nationality' => 'Turkmène'],
            ['name' => 'Tuvalu', 'nationality' => 'Tuvaluan'],
            ['name' => 'Ouganda', 'nationality' => 'Ougandais(e)'],
            ['name' => 'Ukraine', 'nationality' => 'Ukrainien(ne)'],
            ['name' => 'Émirats arabes unis', 'nationality' => 'Emirien(ne)'],
            ['name' => 'Royaume-Uni', 'nationality' => 'Britannique'],
            ['name' => 'États-Unis', 'nationality' => 'Américain(e)'],
            ['name' => 'Uruguay', 'nationality' => 'Uruguayen(ne)'],
            ['name' => 'Ouzbékistan', 'nationality' => 'Ouzbek'],
            ['name' => 'Vanuatu', 'nationality' => 'Vanuatuan'],
            ['name' => 'Venezuela', 'nationality' => 'Vénézuélien(ne)'],
            ['name' => 'Viêt Nam', 'nationality' => 'Vietnamien(ne)'],
            ['name' => 'Yémen', 'nationality' => 'Yéménite'],
            ['name' => 'Zambie', 'nationality' => 'Zambien(ne)'],
            ['name' => 'Zimbabwe', 'nationality' => 'Zimbabween(ne)'],
        ];

        DB::table('countries')->insert($pays);
    }
}

